### ISSUE TITLE
Trimming of sequences when they are less than 60 bp long

### ISSUE THREAD

**Issue by teofiln** [teofiln/gene.editing.dash#1]
![image](https://user-images.githubusercontent.com/2613403/154825062-55313268-74e0-40ba-812f-b825efd30002.png)

**Comment by teofiln** [comment]
Solved this by:
1. checking if the sequence is < than 30 bp
 - if yes, print entire alignment
 - if no:
       - get the midpoint
       - and then switch to mid +/5, 10, or 15 dependent on user choice for aln length

Will become available in the next release.

**Comment by rwangVorbio** [comment]
@teofiln 
the new version didn't fix the issue, instead after deploying the app, it directly:
1) **overwrite the AllExperimentMetaData.RDS**
![image](https://user-images.githubusercontent.com/100057081/154828752-c4f6ea64-87a8-4b30-b7d4-4426acbee25c.png)

2) replace the last dataset into `AMP1046-001-short-aln`:
![image](https://user-images.githubusercontent.com/100057081/154828781-6ce6629b-1d57-441a-b37a-baa200733ee0.png)

3) trigger the app a crash after I click this `AMP1046-001-short-aln`:
 
![image](https://user-images.githubusercontent.com/100057081/154828792-3c05c58c-eea7-4178-8438-cc87d72bc4d4.png)


Just FYI, the correct timestamp of AllExperimentMetaData.RDS and list of dataset should be:
![image](https://user-images.githubusercontent.com/100057081/154828810-bc009da7-5353-46bc-a695-e78307b067a6.png)

![image](https://user-images.githubusercontent.com/100057081/154828814-ae19a767-f63b-470d-93e1-429c75aefc67.png)

**Comment by teofiln** [comment]
Hi @rwangVorbio 

1. Overwrite the metadata file. This is expected. I push the local contents of the package. I cannot know what you have in production context. We can decide to ignore all data objects in the repository so that we can push clean code without data, and your local instance will have real data, while my local instance will have fake data. Other than this, there is nothing else but to remember to replace the metadata in `inst/META` and the data in `inst/DATA` every time you deploy. It is expected that as the variety and complexity of project grows, we will have issues like this often.

2. Is a byproduct of 1. I added a row in the metadata table for a project `AMP1046-001-short-aln`. This RDS is exactly like AMP1046-001 except the sequence columns are 20 bp instead of 60 pb. So that I can test the fix for the issue you reported with shorter sequences.   

3. Is due to the file `AMP1046-001-short-aln.qs` not being pushed to github. This is my fault. I had set git to ignore `qs` files, so it did not track and push that to the remote. I can send you that file, but it does not matter much whether it works with my test fake data. Rather, can you repeat the deployment that you did earlier and test whether the real project with 20bp alignments works in the app.

Thanks!

**Comment by rwangVorbio** [comment]
hi @teofiln ,
thanks for the clarification. I now reinstall this version through del the `ins/DATA` and 'ins/META` and copy the back-up corresponding folders back. It now works. I agree with your point, for the future version let's keep  `ins/DATA` and 'ins/META` as empty. Thanks!

![image](https://user-images.githubusercontent.com/100057081/154829995-db566a7b-6e61-4c2b-8143-326fe181ce3b.png)

**Comment by teofiln** [comment]
Closing this issue. @rwangVorbio feel free to re-open if needed. Or open an new issue.
