### ISSUE TITLE
Bugs in sequence alignment: redundant row, group columns not working

### ISSUE THREAD

**Issue by rwangVorbio** [teofiln/gene.editing.dash#2]
Hi @teofiln,
There are a few bugs in the `Sequence alignment` section:
1) Each unique **TargetId + GrnaSequence + Alignment + NMutated + NDeleted + NInserted** should only have one row in this table, while I current can see some redundant in the 0.2.3:
![image](https://user-images.githubusercontent.com/100057081/154830162-b047d306-59ed-44d6-b9e8-9e662eeea63e.png)

2) We don't need to display any sample metadata columns (e.g., concentration) for the `Sequence alignment` section.

3) I don't know what `group columns` are expected to do, but currently, it does not work in this section. Once I select a column using this function, none of the rows will show up. 
![image](https://user-images.githubusercontent.com/100057081/154830378-93e22c08-d4f3-42f7-a814-54ccb6e8ff23.png)
**Due to our very tight timeline for this project, please either**
a) delete this function in `Sequence alignment` section
or
b) change this function as `Set sample sort meta columns`: after selection of this, the sample columns will be re-ordered by the selected metadata columns. For example, if I select `concentration`, then the sample columns with the same concentration will be displayed together.

**Comment by teofiln** [comment]
@rwangVorbio 

Please try v0.2.4 (just pushed) for a fix on the grouping column. When you select a grouping variable, the table should be grouped and sorted by the levels of selected variable (as you describe in b/ above)

**Comment by teofiln** [comment]
For your point 1 -- redundant rows. 

To make sure I understand. Does this mean we should group **only** by `TargetId + GrnaSequence + Alignment + NMutated + NDeleted + NInserted`, and **not** by sample metadata columns (like Group, Concentration...)? It makes sense, because it's the same genotype in different treatments. But on the other hand, this is not compatible with filtering and grouping by metadata. Because if the same genotype was present in multiple treatments, the rows somehow how to be repeated. 

Should I remove the meta data columns + filtering and grouping by metadata? if yes, this would involve:

1. change in the prep function to not join
2. refactor of the shiny module to not use these dropdowns

**Comment by teofiln** [comment]
I suppose we can keep the grouping, but just not group by metadata fields. Only fields from the table itself?

**Comment by rwangVorbio** [comment]
Hi @teofiln, correct,  for `sequence alignment` section, it should only group by `TargetId + GrnaSequence + Alignment + NMutated + NDeleted + NInserted` 
And filtering for this table will be only used to filter the sample columns out of the table.  I don't get your point on `Because if the same genotype was present in multiple treatments, then rows have to be repeated.` But if this is too complicated for you please just keep `Target id` and 'sample name` in the filtering option for `sequence alignment` section.

**Comment by teofiln** [comment]
Hi @rwangVorbio 

Changed to look like this:
![image](https://user-images.githubusercontent.com/2613403/154899933-e7e6ef7b-7fbd-417a-9d4a-bf0c36a39665.png)

I also removed the sample meta data fields from filters and groups/hiding. And fixed the sequence highlight.

Please check in v0.2.5.

**Comment by rwangVorbio** [comment]
Hi @teofiln,
thanks for fixing this. Could you point out to me where is v0.2.5? It seems not in the Release section...

**Comment by teofiln** [comment]
yes, I just added it: https://github.com/teofiln/gene.editing.dash/releases/tag/0.2.5

**Comment by rwangVorbio** [comment]
just checked, the duplicated rows have been fixed, however, all the table views can not scroll at horizontal:
https://github.com/teofiln/gene.editing.dash/issues/4

**Comment by teofiln** [comment]
OK. lets keep that discussion in #4. I'll close this as the main topic is solved.
