### ISSUE TITLE
Horizontal scrolling does not work in all the table view

### ISSUE THREAD

**Issue by rwangVorbio** [teofiln/gene.editing.dash#4]
Hi @teofiln 
It seems in 0.2.5 all the current horizontal scrolling does not work in all the table views. For example, the scrolling can not let the browser   display the last few columns in each table:
1) Reads QC
![image](https://user-images.githubusercontent.com/100057081/154905380-24c90f81-cbef-4bdd-af54-97907e5665c7.png)

2) sequence alignment
![image](https://user-images.githubusercontent.com/100057081/154905452-c9e5d404-d262-4829-afb8-221e1e525f32.png)

3) Allele frequency
![image](https://user-images.githubusercontent.com/100057081/154905505-0f395b2e-e0cf-4812-805b-f6667c342397.png)

**Comment by teofiln** [comment]
Hi @rwangVorbio 
Hm. This is unexpected.

By default, we are displaying 100 rows. Can you scroll down the page and look for a horizontal scroll bar? I think the scroll bars you are showing here are from the browser window, not the table itself?

Or change the number of records to 25 and maybe the scroll bar will be visible at the bottom of the screen?

This is what I have on the app deployed here: https://diatom.shinyapps.io/gene_editing_dashboard/
![image](https://user-images.githubusercontent.com/2613403/154986342-0412a349-b525-4574-8f50-0c72973da7be.png)

**Comment by rwangVorbio** [comment]
@teofiln ah, thanks for pointing it out, it is indeed from the browser window other than the table. Sorry for the confusion, you can close this ticket. At the same time, let's try to reset the default columns as https://github.com/teofiln/gene.editing.dash/issues/5 , so that users may not need to use scrolling to adjust the table, thanks!

**Comment by teofiln** [comment]
OK. I'll reset the default columns as per #5  for the next minor release (maybe later today or tonight).
