### ISSUE TITLE
Default columns in QC and allele frequency table

### ISSUE THREAD

**Issue by rwangVorbio** [teofiln/gene.editing.dash#5]
Hi @teofiln ,
Let's set the default display columns (both columns and orders) for QC and allele frequency table as below:
- **QC**
Sample name, Target id, Total pairs, Trimming pair removed, Combined pairs, Percent combined, Total reads aligned, Percent aligned, Usable reads total, Percent usable total reads

- **allele frequency**
Target id, Experiment id, Sample Name, Gdna id, Indel, Subs, Indel+Subs, Grand Total

Thanks!

**Comment by teofiln** [comment]
@rwangVorbio 

Updated like so:

![image](https://user-images.githubusercontent.com/2613403/155057335-71abe844-213d-4170-9e00-eeda34e5df1a.png)

and 

![image](https://user-images.githubusercontent.com/2613403/155057386-1cde3e88-3e7f-4061-8424-f62836ce85c6.png)

**Comment by teofiln** [comment]
v0.2.6 is ready: https://github.com/teofiln/gene.editing.dash/releases/tag/v0.2.6

Please test and let me know. 
Thanks!

**Comment by rwangVorbio** [comment]
@teofiln, just tested, it works now, you can close this ticket
