### ISSUE TITLE
project search bar is disappeared once one project is selected

### ISSUE THREAD

**Issue by rwangVorbio** [teofiln/gene.editing.dash#6]
@teofiln ,
In the current version, the search bar will be disappeared after one project is selected (tested in both R connect and your shinyapps). We need to at least have a reset button to enable users to re-search the project. 

![image](https://user-images.githubusercontent.com/100057081/155062969-7ba0cb11-cf28-4995-951e-e90cd6c9c92a.png)

**Comment by teofiln** [comment]
I see the problem. Will push a fix today.

**Comment by teofiln** [comment]
closing this too. fyi @rwangVorbio
