### ISSUE TITLE
Improvement on Editing rate summary plot, flip x and y

### ISSUE THREAD

**Issue by rwangVorbio** [teofiln/gene.editing.dash#8]
@teofiln , just a quick question:
**Is it possible that we can have an improvement feature for the Editing rate summary plot**:
The user can configure whether to flip x and y for this plot. Since in our real data set, there are too many samples to show them in horizontal :
![image](https://user-images.githubusercontent.com/100057081/155560066-8fc4d47d-16d0-4fc4-b6a2-0dc892e74533.png)

**Comment by teofiln** [comment]
Yep. We can add a checkbox in the app to switch on coord_flip in the plotting function.

**Comment by rwangVorbio** [comment]
@teofiln , thanks!
